"""init

Revision ID: 41bbb0062048
Revises: 
Create Date: 2024-07-22 03:28:50.201364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41bbb0062048'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('ParentID', sa.Integer(), nullable=True),
    sa.Column('IsUsable', sa.Boolean(), nullable=True),
    sa.Column('DeleteTime', sa.DateTime(), nullable=True),
    sa.Column('CreateTime', sa.DateTime(), nullable=True),
    sa.Column('UpdateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NickName', sa.String(length=255), nullable=False),
    sa.Column('ZhName', sa.String(length=255), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Phone', sa.String(length=11), nullable=True),
    sa.Column('DepartmentID', sa.Integer(), nullable=True),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('IsUsable', sa.Boolean(), nullable=True),
    sa.Column('DeleteTime', sa.DateTime(), nullable=True),
    sa.Column('CreateTime', sa.DateTime(), nullable=True),
    sa.Column('UpdateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org_user')
    op.drop_table('org_department')
    # ### end Alembic commands ###
